import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import { api } from "@/utils/api";
import { useEffect, useContext } from "react";
import Header from "@/components/Header";
import UserContext from "@/context/UserContext";
import { useRouter } from "next/router";
import Spinner from "@/components/Spinner";

export default function Home() {
  const { authUser, userLoading } = useContext(UserContext);

  const router = useRouter();
  useEffect(() => {
    if (!authUser.user && !userLoading) {
      router.push("/user/login");
    } else if (authUser.user && !userLoading && !authUser.user.isVerified) {
      router.push("/user/verify");
    }
  }, [authUser, userLoading]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {userLoading ? (
        <Spinner />
      ) : (
        <main className="mt-[64px] flex min-h-screen items-start justify-center">
          <div className="flex w-2/4 flex-col items-center justify-center gap-[16px]">
            <h1 className="text-center text-[32px] font-[500]">
              Go to categories to start shopping
            </h1>
            <button
              className="w-3/4 rounded-[6px] bg-black p-[18px] font-[500] text-[#FFFFFF]"
              onClick={(e) => {
                e.preventDefault();
                router.push("/category");
              }}
            >
              VISIT CATEGORIES
            </button>
          </div>
        </main>
      )}
    </>
  );
}
